version: '3.1'
services:
  db:
    image: mysql:8
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # volumes:
    #   - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubuntu
      MYSQL_DATABASE: groupomania

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    db_data:
